Script started on 2023-10-20 14:41:16-04:00 [TERM="xterm-256color" TTY="/dev/pts/10" COLUMNS="122" LINES="57"]
]0;jwong988@compute:~/courses/cs2211/Asn/asn3[?2004h[jwong988@compute asn3]$ ./ss_integer
[?2004lInput an integer: 1234567890
      _   _       _   _   _   _   _   _ 
  |   _|  _| |_| |_  |_    | |_| |_| | |
  |  |_   _|   |  _| |_|   | |_|  _| |_|
Do you wish to continue (Y/N)? Y
Input an integer: 13243546
      _   _       _   _       _ 
  |   _|  _| |_|  _| |_  |_| |_ 
  |   _| |_    |  _|  _|   | |_|
Do you wish to continue (Y/N)? y
Input an integer: 90348
  _   _   _       _ 
 |_| | |  _| |_| |_|
  _| |_|  _|   | |_|
Do you wish to continue (Y/N)? N
]0;jwong988@compute:~/courses/cs2211/Asn/asn3[?2004h[jwong988@compute asn3]$ exit
[?2004lexit

Script done on 2023-10-20 14:42:15-04:00 [COMMAND_EXIT_CODE="0"]
