Script started on 2023-10-06 15:00:25-04:00 [TERM="xterm-256color" TTY="/dev/pts/34" COLUMNS="108" LINES="54"]
]0;jwong988@compute:~/courses/cs2211/Asn/asn2[?2004h[jwong988@compute asn2]$ ./power2_calculator
[?2004lEnter the exponent value: 10  20
2 to the power of 20 is 1048576.
Enter the exponent value: 10
2 to the power of 10 is 1024.
Enter the exponent value: 9
2 to the power of 9 is 512.
Enter the exponent value: 8
2 to the power of 8 is 256.
Enter the exponent value: 7
2 to the power of 7 is 128.
Enter the exponent value: 6
2 to the power of 6 is 64.
Enter the exponent value: 5
2 to the power of 5 is 32.
Enter the exponent value: 4
2 to the power of 4 is 16.
Enter the exponent value: 3
2 to the power of 3 is 8.
Enter the exponent value: 2
2 to the power of 2 is 4.
Enter the exponent value: 1
2 to the power of 1 is 2.
Enter the exponent value: 0
2 to the power of 0 is 1.
]0;jwong988@compute:~/courses/cs2211/Asn/asn2[?2004h[jwong988@compute asn2]$ exit
[?2004lexit

Script done on 2023-10-06 15:00:52-04:00 [COMMAND_EXIT_CODE="0"]
